limit_req_zone $binary_remote_addr zone=api_limit:1m rate=10r/m;

server {
    location / {
        root /var/www/html;
    }

    location /api/ {
        limit_req zone=api_limit burst=5 nodelay;
        limit_req_status 429;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://node:8181/;
    }
}
